// utils/projectData.js
// Este archivo contiene todos los datos del proyecto JAI-VIER

export const projectData = {
	name: "JAI-VIER - Herramienta de Administración de Proyectos",
	startDate: "2025-02-10",
	endDate: "2025-06-02",
	currentSprint: "Sprint 5",
	stats: {
		totalTasks: 49,
		completedTasks: 6,
		remainingTasks: 43,
		totalEstimatedHours: 483,
		completedEstimatedHours: 48,
		remainingHours: 435,
		completionPercentage: 10,
		totalActualHours: 36,
	},
};

export const sprintData = {
	"Sprint 1": {
		totalTasks: 3,
		completedTasks: 3,
		remainingTasks: 0,
		totalEstimatedHours: 24,
		completedEstimatedHours: 24,
		remainingHours: 0,
		completionPercentage: 100,
		startDate: "2025-02-10",
		endDate: "2025-02-16",
	},
	"Sprint 2": {
		totalTasks: 3,
		completedTasks: 3,
		remainingTasks: 0,
		totalEstimatedHours: 24,
		completedEstimatedHours: 24,
		remainingHours: 0,
		completionPercentage: 100,
		startDate: "2025-02-17",
		endDate: "2025-02-23",
	},
	"Sprint 3": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 28,
		completedEstimatedHours: 0,
		remainingHours: 28,
		completionPercentage: 0,
		startDate: "2025-02-24",
		endDate: "2025-03-02",
	},
	"Sprint 4": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 24,
		completedEstimatedHours: 0,
		remainingHours: 24,
		completionPercentage: 0,
		startDate: "2025-03-03",
		endDate: "2025-03-09",
	},
	"Sprint 5": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 29,
		completedEstimatedHours: 0,
		remainingHours: 29,
		completionPercentage: 0,
		startDate: "2025-03-10",
		endDate: "2025-03-16",
	},
	"Sprint 6": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-03-17",
		endDate: "2025-03-23",
	},
	"Sprint 7": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-03-24",
		endDate: "2025-03-30",
	},
	"Sprint 8": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-03-31",
		endDate: "2025-04-06",
	},
	"Sprint 9": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-04-07",
		endDate: "2025-04-13",
	},
	"Sprint 10": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-04-14",
		endDate: "2025-04-20",
	},
	"Sprint 11": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-04-21",
		endDate: "2025-04-27",
	},
	"Sprint 12": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-04-28",
		endDate: "2025-05-04",
	},
	"Sprint 13": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-05-05",
		endDate: "2025-05-11",
	},
	"Sprint 14": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-05-12",
		endDate: "2025-05-18",
	},
	"Sprint 15": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-05-19",
		endDate: "2025-05-25",
	},
	"Sprint 16": {
		totalTasks: 3,
		completedTasks: 0,
		remainingTasks: 3,
		totalEstimatedHours: 30,
		completedEstimatedHours: 0,
		remainingHours: 30,
		completionPercentage: 0,
		startDate: "2025-05-26",
		endDate: "2025-06-02",
	},
};

export const memberData = {
	Aaron3312: {
		totalTasks: 23,
		completedTasks: 6,
		inProgressTasks: 1,
		pendingTasks: 16,
		estimatedHours: 117.3,
	},
	arambs22: {
		totalTasks: 15,
		completedTasks: 4,
		inProgressTasks: 0,
		pendingTasks: 11,
		estimatedHours: 49.8,
	},
	Banales2: {
		totalTasks: 19,
		completedTasks: 5,
		inProgressTasks: 1,
		pendingTasks: 13,
		estimatedHours: 89.3,
	},
	"DJeison-DVT": {
		totalTasks: 23,
		completedTasks: 4,
		inProgressTasks: 0,
		pendingTasks: 19,
		estimatedHours: 110.3,
	},
	Fercubos: {
		totalTasks: 16,
		completedTasks: 4,
		inProgressTasks: 0,
		pendingTasks: 12,
		estimatedHours: 55.8,
	},
	RomeoThePickleTec: {
		totalTasks: 17,
		completedTasks: 4,
		inProgressTasks: 0,
		pendingTasks: 13,
		estimatedHours: 60.3,
	},
};

export const fullBurndownData = [
	{ date: "2025-02-10", ideal: 483, actual: 483, sprint: "Sprint 1" },
	{ date: "2025-02-16", ideal: 458, actual: 470, sprint: "Sprint 1" },
	{ date: "2025-02-17", ideal: 450, actual: 470, sprint: "Sprint 2" },
	{ date: "2025-02-23", ideal: 425, actual: 459, sprint: "Sprint 2" },
	{ date: "2025-02-24", ideal: 410, actual: 459, sprint: "Sprint 3" },
	{ date: "2025-03-02", ideal: 395, actual: 435, sprint: "Sprint 3" },
	{ date: "2025-03-03", ideal: 385, actual: 435, sprint: "Sprint 4" },
	{ date: "2025-03-09", ideal: 360, actual: 435, sprint: "Sprint 4" },
	{ date: "2025-03-10", ideal: 345, actual: 435, sprint: "Sprint 5" },
	{ date: "2025-03-16", ideal: 330, actual: 420, sprint: "Sprint 5" },
	{ date: "2025-03-17", ideal: 315, actual: 420, sprint: "Sprint 6" },
	{ date: "2025-03-23", ideal: 290, actual: 405, sprint: "Sprint 6" },
	{ date: "2025-03-24", ideal: 275, actual: 405, sprint: "Sprint 7" },
	{ date: "2025-03-30", ideal: 250, actual: 390, sprint: "Sprint 7" },
	{ date: "2025-03-31", ideal: 245, actual: 390, sprint: "Sprint 8" },
	{ date: "2025-04-06", ideal: 230, actual: 375, sprint: "Sprint 8" },
	{ date: "2025-04-07", ideal: 220, actual: 375, sprint: "Sprint 9" },
	{ date: "2025-04-13", ideal: 205, actual: 360, sprint: "Sprint 9" },
	{ date: "2025-04-14", ideal: 195, actual: 360, sprint: "Sprint 10" },
	{ date: "2025-04-20", ideal: 175, actual: 330, sprint: "Sprint 10" },
	{ date: "2025-04-21", ideal: 165, actual: 330, sprint: "Sprint 11" },
	{ date: "2025-04-27", ideal: 145, actual: 300, sprint: "Sprint 11" },
	{ date: "2025-04-28", ideal: 135, actual: 300, sprint: "Sprint 12" },
	{ date: "2025-05-04", ideal: 115, actual: 270, sprint: "Sprint 12" },
	{ date: "2025-05-05", ideal: 108, actual: 270, sprint: "Sprint 13" },
	{ date: "2025-05-11", ideal: 95, actual: 240, sprint: "Sprint 13" },
	{ date: "2025-05-12", ideal: 85, actual: 240, sprint: "Sprint 14" },
	{ date: "2025-05-18", ideal: 68, actual: 180, sprint: "Sprint 14" },
	{ date: "2025-05-19", ideal: 55, actual: 180, sprint: "Sprint 15" },
	{ date: "2025-05-25", ideal: 38, actual: 120, sprint: "Sprint 15" },
	{ date: "2025-05-26", ideal: 25, actual: 120, sprint: "Sprint 16" },
	{ date: "2025-06-02", ideal: 0, actual: 0, sprint: "Sprint 16" },
];

export const tasks = [
	{
		id: 1,
		title: "Certificación OCI",
		sprint: "Sprint 1",
		estimate: 8,
		actual: 4,
		status: "Done",
		completionDate: "2025-02-14",
		assignees: [
			"Aaron3312",
			"arambs22",
			"Banales2",
			"DJeison-DVT",
			"Fercubos",
			"RomeoThePickleTec",
		],
	},
	{
		id: 2,
		title: "Documento de Planificación del Proyecto",
		sprint: "Sprint 1",
		estimate: 8,
		actual: 2,
		status: "Done",
		completionDate: "2025-02-15",
		assignees: ["Aaron3312"],
	},
	{
		id: 3,
		title: "Análisis de Requerimientos",
		sprint: "Sprint 1",
		estimate: 8,
		actual: 4,
		status: "Done",
		completionDate: "2025-02-16",
		assignees: [
			"Aaron3312",
			"arambs22",
			"Banales2",
			"DJeison-DVT",
			"Fercubos",
			"RomeoThePickleTec",
		],
	},
	{
		id: 4,
		title: "Primera Presentación para Oracle",
		sprint: "Sprint 2",
		estimate: 6,
		actual: 8,
		status: "Done",
		completionDate: "2025-02-20",
		assignees: [
			"Aaron3312",
			"arambs22",
			"Banales2",
			"DJeison-DVT",
			"Fercubos",
			"RomeoThePickleTec",
		],
	},
	{
		id: 5,
		title: "Despliegue Inicial de Prueba",
		sprint: "Sprint 2",
		estimate: 8,
		actual: 14,
		status: "Done",
		completionDate: "2025-02-22",
		assignees: ["Aaron3312", "Banales2"],
	},
	{
		id: 6,
		title: "Plan de Pruebas",
		sprint: "Sprint 2",
		estimate: 10,
		actual: 4,
		status: "Done",
		completionDate: "2025-02-23",
		assignees: [
			"Aaron3312",
			"arambs22",
			"Banales2",
			"DJeison-DVT",
			"Fercubos",
			"RomeoThePickleTec",
		],
	},
	{
		id: 7,
		title: "Configurar Recursos Básicos en OCI",
		sprint: "Sprint 3",
		estimate: 10,
		actual: null,
		status: "In progress",
		completionDate: null,
		assignees: ["Aaron3312", "Banales2"],
	},
	{
		id: 8,
		title: "Implementar Oracle Autonomous Database",
		sprint: "Sprint 3",
		estimate: 8,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT", "RomeoThePickleTec"],
	},
	{
		id: 9,
		title: "Configurar Entornos Kubernetes",
		sprint: "Sprint 3",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2"],
	},
	{
		id: 10,
		title: "Implementar Pipeline CI/CD Básico",
		sprint: "Sprint 4",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "Banales2"],
	},
	{
		id: 11,
		title: "Configurar Entornos de Desarrollo",
		sprint: "Sprint 4",
		estimate: 6,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["RomeoThePickleTec"],
	},
	{
		id: 12,
		title: "Configurar API Gateway",
		sprint: "Sprint 4",
		estimate: 8,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT"],
	},
	{
		id: 13,
		title: "Crear Estructura Base de Microservicios",
		sprint: "Sprint 5",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "DJeison-DVT"],
	},
	{
		id: 14,
		title: "Preparar Integración con Telegram",
		sprint: "Sprint 5",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Fercubos", "arambs22"],
	},
	{
		id: 15,
		title: "Definir Contratos de API",
		sprint: "Sprint 5",
		estimate: 9,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT", "Aaron3312"],
	},
	{
		id: 16,
		title: "Implementar Microservicio de Gestión de Usuarios",
		sprint: "Sprint 6",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT"],
	},
	{
		id: 17,
		title: "Configurar Autenticación y Autorización",
		sprint: "Sprint 6",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["RomeoThePickleTec"],
	},
	{
		id: 18,
		title: "Implementar Modelos de Base de Datos",
		sprint: "Sprint 6",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2", "DJeison-DVT"],
	},
	{
		id: 19,
		title: "Implementar Microservicio de Gestión de Proyectos",
		sprint: "Sprint 7",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312"],
	},
	{
		id: 20,
		title: "Implementar APIs CRUD para Proyectos",
		sprint: "Sprint 7",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "DJeison-DVT"],
	},
	{
		id: 21,
		title: "Configurar Relaciones entre Entidades",
		sprint: "Sprint 7",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2"],
	},
	{
		id: 22,
		title: "Implementar Microservicio de Gestión de Tareas",
		sprint: "Sprint 8",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "DJeison-DVT"],
	},
	{
		id: 23,
		title: "Implementar Workflow de Estados de Tareas",
		sprint: "Sprint 8",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT"],
	},
	{
		id: 24,
		title: "Implementar Seguimiento de Tiempo",
		sprint: "Sprint 8",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2"],
	},
	{
		id: 25,
		title: "Implementar Microservicio de KPIs",
		sprint: "Sprint 9",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2"],
	},
	{
		id: 26,
		title: "Desarrollar Algoritmos para Cálculo de Métricas",
		sprint: "Sprint 9",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2", "Aaron3312"],
	},
	{
		id: 27,
		title: "Implementar APIs para Consulta de KPIs",
		sprint: "Sprint 9",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT"],
	},
	{
		id: 28,
		title: "Implementar Pruebas Unitarias",
		sprint: "Sprint 10",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Fercubos"],
	},
	{
		id: 29,
		title: "Implementar Pruebas de Integración",
		sprint: "Sprint 10",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["arambs22", "Fercubos"],
	},
	{
		id: 30,
		title: "Implementar Seguridad en APIs",
		sprint: "Sprint 10",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["RomeoThePickleTec"],
	},
	{
		id: 31,
		title: "Configurar Proyecto Frontend",
		sprint: "Sprint 11",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312"],
	},
	{
		id: 32,
		title: "Desarrollar Módulo de Autenticación",
		sprint: "Sprint 11",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "arambs22"],
	},
	{
		id: 33,
		title: "Desarrollar Dashboard Principal",
		sprint: "Sprint 11",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312"],
	},
	{
		id: 34,
		title: "Desarrollar Módulo de Gestión de Proyectos (Frontend)",
		sprint: "Sprint 12",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "arambs22"],
	},
	{
		id: 35,
		title: "Desarrollar Módulo de Gestión de Tareas (Frontend)",
		sprint: "Sprint 12",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "arambs22"],
	},
	{
		id: 36,
		title: "Implementar Visualizaciones de KPIs",
		sprint: "Sprint 12",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "Banales2"],
	},
	{
		id: 37,
		title: "Desarrollar Estructura Base del Chatbot",
		sprint: "Sprint 13",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT", "Fercubos"],
	},
	{
		id: 38,
		title: "Implementar Comandos para Gestión de Proyectos",
		sprint: "Sprint 13",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT"],
	},
	{
		id: 39,
		title: "Implementar Comandos para Gestión de Tareas",
		sprint: "Sprint 13",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["DJeison-DVT", "Banales2"],
	},
	{
		id: 40,
		title: "Integrar Frontend con Backend",
		sprint: "Sprint 14",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "DJeison-DVT"],
	},
	{
		id: 41,
		title: "Integrar Chatbot con Backend",
		sprint: "Sprint 14",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2", "DJeison-DVT"],
	},
	{
		id: 42,
		title: "Implementar Sistema de Notificaciones",
		sprint: "Sprint 14",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["RomeoThePickleTec", "Fercubos"],
	},
	{
		id: 43,
		title: "Realizar Pruebas de Rendimiento",
		sprint: "Sprint 15",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["arambs22", "Fercubos"],
	},
	{
		id: 44,
		title: "Realizar Pruebas de Seguridad",
		sprint: "Sprint 15",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["RomeoThePickleTec"],
	},
	{
		id: 45,
		title: "Realizar Pruebas de Usabilidad",
		sprint: "Sprint 15",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["arambs22", "Fercubos"],
	},
	{
		id: 46,
		title: "Preparar Entorno de Producción",
		sprint: "Sprint 16",
		estimate: 10,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Banales2", "RomeoThePickleTec"],
	},
	{
		id: 47,
		title: "Despliegue de Componentes",
		sprint: "Sprint 16",
		estimate: 8,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["Aaron3312", "Banales2"],
	},
	{
		id: 48,
		title: "Documentación Final",
		sprint: "Sprint 16",
		estimate: 6,
		actual: null,
		status: "Backlog",
		completionDate: null,
		assignees: ["RomeoThePickleTec", "Fercubos"],
	},
];

export const colors = {
	ideal: "#8884d8",
	actual: "#82ca9d",
	completed: "#4caf50",
	inProgress: "#ff9800",
	pending: "#f44336",
	today: "#e91e63",
};

export const members = [
	"all",
	"Aaron3312",
	"arambs22",
	"Banales2",
	"DJeison-DVT",
	"Fercubos",
	"RomeoThePickleTec",
];

// Fecha actual para la línea de referencia (simulamos que es 28 de febrero de 2025)
export const today = "2025-02-28";

export const sprints = [
	"all",
	"Sprint 1",
	"Sprint 2",
	"Sprint 3",
	"Sprint 4",
	"Sprint 5",
	"Sprint 6",
	"Sprint 7",
	"Sprint 8",
	"Sprint 9",
	"Sprint 10",
	"Sprint 11",
	"Sprint 12",
	"Sprint 13",
	"Sprint 14",
	"Sprint 15",
	"Sprint 16",
];
